const uint8_t layout[LAYOUT_ROW_SIZE][LAYOUT_COLUMN_SIZE] = {
    { KC_NUM_LOCK, KC_KEYPAD_DIVIDE, KC_KEYPAD_MULTIPLY, KC_KEYPAD_SUBTRACT },
    { KC_KEYPAD_7, KC_KEYPAD_8,      KC_KEYPAD_9,        KC_KEYPAD_ADD      },
    { KC_KEYPAD_4, KC_KEYPAD_5,      KC_KEYPAD_6,        KC_KEYPAD_ENTER    },
    { KC_KEYPAD_1, KC_KEYPAD_2,      KC_KEYPAD_3,        KC_KEYPAD_PERIOD   },
};